package com.flx.flxoa.info.market.entity;
// Generated 2018-12-25 15:56:29 by Hibernate Tools 5.0.6.Final

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * HxArea generated by hbm2java
 */
@Entity
@Table(name = "hx_area", catalog = "flxoa")
public class HxArea implements java.io.Serializable {

	private String areaCode;
	private String areaName;
	private Integer aa;
	private Integer aa2;
	private Integer aa1;

	public HxArea() {
	}

	public HxArea(String areaCode) {
		this.areaCode = areaCode;
	}

	public HxArea(String areaCode, String areaName, Integer aa) {
		this.areaCode = areaCode;
		this.areaName = areaName;
		this.aa = aa;
	}

	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	public Integer getAa() {
		return this.aa;
	}

	public void setAa(Integer aa) {
		this.aa = aa;
	}

}
