package com.flx.flxoa.info.market.entity;
// Generated 2018-11-9 19:09:53 by Hibernate Tools 5.1.7.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Hx generated by hbm2java
 */
@Entity
@Table(name = "hx", catalog = "flxoa")
public class Hx implements java.io.Serializable {

	private HxId id;

	public Hx() {
	}

	public Hx(HxId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cropOfferId", column = @Column(name = "CropOfferID", nullable = false)),
			@AttributeOverride(name = "regionCode", column = @Column(name = "RegionCode", length = 6)),
			@AttributeOverride(name = "regionName", column = @Column(name = "RegionName", length = 30)),
			@AttributeOverride(name = "cropCategoryCode", column = @Column(name = "CropCategoryCode", length = 6)),
			@AttributeOverride(name = "cropCategoryName", column = @Column(name = "CropCategoryName", length = 50)),
			@AttributeOverride(name = "cropOfferStr", column = @Column(name = "CropOfferStr", length = 100)),
			@AttributeOverride(name = "offerDate", column = @Column(name = "OfferDate", length = 10)),
			@AttributeOverride(name = "price", column = @Column(name = "Price", precision = 10, scale = 0)),
			@AttributeOverride(name = "unit", column = @Column(name = "Unit")),
			@AttributeOverride(name = "unitName", column = @Column(name = "UnitName", length = 50)),
			@AttributeOverride(name = "todayTrend", column = @Column(name = "TodayTrend", precision = 12, scale = 0)),
			@AttributeOverride(name = "fiveDayTrend", column = @Column(name = "FiveDayTrend", precision = 12, scale = 0)),
			@AttributeOverride(name = "weekAverage", column = @Column(name = "WeekAverage", precision = 10, scale = 0)),
			@AttributeOverride(name = "weekTrend", column = @Column(name = "WeekTrend", precision = 12, scale = 0)),
			@AttributeOverride(name = "reason", column = @Column(name = "Reason", length = 100)),
			@AttributeOverride(name = "browseCount", column = @Column(name = "BrowseCount")),
			@AttributeOverride(name = "approvalState", column = @Column(name = "ApprovalState")),
			@AttributeOverride(name = "releaseState", column = @Column(name = "ReleaseState")),
			@AttributeOverride(name = "userId", column = @Column(name = "UserID")),
			@AttributeOverride(name = "userRealName", column = @Column(name = "UserRealName", length = 50)),
			@AttributeOverride(name = "offerDateTime", column = @Column(name = "OfferDateTime", length = 19)) })
	public HxId getId() {
		return this.id;
	}

	public void setId(HxId id) {
		this.id = id;
	}

	public void setDeleteFlag(String string) {
		// TODO Auto-generated method stub
		
	}

}
