package com.flx.flxoa.info.market.entity;
// Generated 2018-11-9 19:09:53 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HxCropsource generated by hbm2java
 */
@Entity
@Table(name = "hx_cropsource", catalog = "flxoa")
public class HxCropsource implements java.io.Serializable {

	private int cropSourceId;
	private HxCropcategory hxCropcategory;
	private HxSource hxSource;
	private String sourceName;

	public HxCropsource() {
	}

	public HxCropsource(int cropSourceId) {
		this.cropSourceId = cropSourceId;
	}

	public HxCropsource(int cropSourceId, HxCropcategory hxCropcategory, HxSource hxSource, String sourceName) {
		this.cropSourceId = cropSourceId;
		this.hxCropcategory = hxCropcategory;
		this.hxSource = hxSource;
		this.sourceName = sourceName;
	}

	@Id

	@Column(name = "CropSourceID", unique = true, nullable = false)
	public int getCropSourceId() {
		return this.cropSourceId;
	}

	public void setCropSourceId(int cropSourceId) {
		this.cropSourceId = cropSourceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CropCategoryCode")
	public HxCropcategory getHxCropcategory() {
		return this.hxCropcategory;
	}

	public void setHxCropcategory(HxCropcategory hxCropcategory) {
		this.hxCropcategory = hxCropcategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SourceCode")
	public HxSource getHxSource() {
		return this.hxSource;
	}

	public void setHxSource(HxSource hxSource) {
		this.hxSource = hxSource;
	}

	@Column(name = "SourceName", length = 50)
	public String getSourceName() {
		return this.sourceName;
	}

	public void setSourceName(String sourceName) {
		this.sourceName = sourceName;
	}

	public void setDeleteFlag(String string) {
		// TODO Auto-generated method stub
		
	}

}
