package com.flx.flxoa.info.market.entity;
// Generated 2018-11-9 19:09:53 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HxFollow generated by hbm2java
 */
@Entity
@Table(name = "hx_follow", catalog = "flxoa")
public class HxFollow implements java.io.Serializable {

	private Integer followId;
	private HxSource hxSource;
	private HxUser hxUser;
	private String sourceName;

	public HxFollow() {
	}

	public HxFollow(HxSource hxSource, HxUser hxUser, String sourceName) {
		this.hxSource = hxSource;
		this.hxUser = hxUser;
		this.sourceName = sourceName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FollowID", unique = true, nullable = false)
	public Integer getFollowId() {
		return this.followId;
	}

	public void setFollowId(Integer followId) {
		this.followId = followId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SourceCode")
	public HxSource getHxSource() {
		return this.hxSource;
	}

	public void setHxSource(HxSource hxSource) {
		this.hxSource = hxSource;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID")
	public HxUser getHxUser() {
		return this.hxUser;
	}

	public void setHxUser(HxUser hxUser) {
		this.hxUser = hxUser;
	}

	@Column(name = "SourceName", length = 50)
	public String getSourceName() {
		return this.sourceName;
	}

	public void setSourceName(String sourceName) {
		this.sourceName = sourceName;
	}

	public void setDeleteFlag(String string) {
		// TODO Auto-generated method stub
		
	}

}
