package com.flx.flxoa.info.market.entity;
// Generated 2018-11-9 19:09:53 by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HxId generated by hbm2java
 */
@Embeddable
public class HxId implements java.io.Serializable {

	private int cropOfferId;
	private String regionCode;
	private String regionName;
	private String cropCategoryCode;
	private String cropCategoryName;
	private String cropOfferStr;
	private Date offerDate;
	private Long price;
	private Integer unit;
	private String unitName;
	private Float todayTrend;
	private Float fiveDayTrend;
	private Long weekAverage;
	private Float weekTrend;
	private String reason;
	private Integer browseCount;
	private Boolean approvalState;
	private Boolean releaseState;
	private Integer userId;
	private String userRealName;
	private Date offerDateTime;

	public HxId() {
	}

	public HxId(int cropOfferId) {
		this.cropOfferId = cropOfferId;
	}

	public HxId(int cropOfferId, String regionCode, String regionName, String cropCategoryCode, String cropCategoryName,
			String cropOfferStr, Date offerDate, Long price, Integer unit, String unitName, Float todayTrend,
			Float fiveDayTrend, Long weekAverage, Float weekTrend, String reason, Integer browseCount,
			Boolean approvalState, Boolean releaseState, Integer userId, String userRealName, Date offerDateTime) {
		this.cropOfferId = cropOfferId;
		this.regionCode = regionCode;
		this.regionName = regionName;
		this.cropCategoryCode = cropCategoryCode;
		this.cropCategoryName = cropCategoryName;
		this.cropOfferStr = cropOfferStr;
		this.offerDate = offerDate;
		this.price = price;
		this.unit = unit;
		this.unitName = unitName;
		this.todayTrend = todayTrend;
		this.fiveDayTrend = fiveDayTrend;
		this.weekAverage = weekAverage;
		this.weekTrend = weekTrend;
		this.reason = reason;
		this.browseCount = browseCount;
		this.approvalState = approvalState;
		this.releaseState = releaseState;
		this.userId = userId;
		this.userRealName = userRealName;
		this.offerDateTime = offerDateTime;
	}

	@Column(name = "CropOfferID", nullable = false)
	public int getCropOfferId() {
		return this.cropOfferId;
	}

	public void setCropOfferId(int cropOfferId) {
		this.cropOfferId = cropOfferId;
	}

	@Column(name = "RegionCode", length = 6)
	public String getRegionCode() {
		return this.regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	@Column(name = "RegionName", length = 30)
	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	@Column(name = "CropCategoryCode", length = 6)
	public String getCropCategoryCode() {
		return this.cropCategoryCode;
	}

	public void setCropCategoryCode(String cropCategoryCode) {
		this.cropCategoryCode = cropCategoryCode;
	}

	@Column(name = "CropCategoryName", length = 50)
	public String getCropCategoryName() {
		return this.cropCategoryName;
	}

	public void setCropCategoryName(String cropCategoryName) {
		this.cropCategoryName = cropCategoryName;
	}

	@Column(name = "CropOfferStr", length = 100)
	public String getCropOfferStr() {
		return this.cropOfferStr;
	}

	public void setCropOfferStr(String cropOfferStr) {
		this.cropOfferStr = cropOfferStr;
	}

	@Column(name = "OfferDate", length = 10)
	public Date getOfferDate() {
		return this.offerDate;
	}

	public void setOfferDate(Date offerDate) {
		this.offerDate = offerDate;
	}

	@Column(name = "Price", precision = 10, scale = 0)
	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

	@Column(name = "Unit")
	public Integer getUnit() {
		return this.unit;
	}

	public void setUnit(Integer unit) {
		this.unit = unit;
	}

	@Column(name = "UnitName", length = 50)
	public String getUnitName() {
		return this.unitName;
	}

	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}

	@Column(name = "TodayTrend", precision = 12, scale = 0)
	public Float getTodayTrend() {
		return this.todayTrend;
	}

	public void setTodayTrend(Float todayTrend) {
		this.todayTrend = todayTrend;
	}

	@Column(name = "FiveDayTrend", precision = 12, scale = 0)
	public Float getFiveDayTrend() {
		return this.fiveDayTrend;
	}

	public void setFiveDayTrend(Float fiveDayTrend) {
		this.fiveDayTrend = fiveDayTrend;
	}

	@Column(name = "WeekAverage", precision = 10, scale = 0)
	public Long getWeekAverage() {
		return this.weekAverage;
	}

	public void setWeekAverage(Long weekAverage) {
		this.weekAverage = weekAverage;
	}

	@Column(name = "WeekTrend", precision = 12, scale = 0)
	public Float getWeekTrend() {
		return this.weekTrend;
	}

	public void setWeekTrend(Float weekTrend) {
		this.weekTrend = weekTrend;
	}

	@Column(name = "Reason", length = 100)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "BrowseCount")
	public Integer getBrowseCount() {
		return this.browseCount;
	}

	public void setBrowseCount(Integer browseCount) {
		this.browseCount = browseCount;
	}

	@Column(name = "ApprovalState")
	public Boolean getApprovalState() {
		return this.approvalState;
	}

	public void setApprovalState(Boolean approvalState) {
		this.approvalState = approvalState;
	}

	@Column(name = "ReleaseState")
	public Boolean getReleaseState() {
		return this.releaseState;
	}

	public void setReleaseState(Boolean releaseState) {
		this.releaseState = releaseState;
	}

	@Column(name = "UserID")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "UserRealName", length = 50)
	public String getUserRealName() {
		return this.userRealName;
	}

	public void setUserRealName(String userRealName) {
		this.userRealName = userRealName;
	}

	@Column(name = "OfferDateTime", length = 19)
	public Date getOfferDateTime() {
		return this.offerDateTime;
	}

	public void setOfferDateTime(Date offerDateTime) {
		this.offerDateTime = offerDateTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HxId))
			return false;
		HxId castOther = (HxId) other;

		return (this.getCropOfferId() == castOther.getCropOfferId())
				&& ((this.getRegionCode() == castOther.getRegionCode()) || (this.getRegionCode() != null
						&& castOther.getRegionCode() != null && this.getRegionCode().equals(castOther.getRegionCode())))
				&& ((this.getRegionName() == castOther.getRegionName()) || (this.getRegionName() != null
						&& castOther.getRegionName() != null && this.getRegionName().equals(castOther.getRegionName())))
				&& ((this.getCropCategoryCode() == castOther.getCropCategoryCode())
						|| (this.getCropCategoryCode() != null && castOther.getCropCategoryCode() != null
								&& this.getCropCategoryCode().equals(castOther.getCropCategoryCode())))
				&& ((this.getCropCategoryName() == castOther.getCropCategoryName())
						|| (this.getCropCategoryName() != null && castOther.getCropCategoryName() != null
								&& this.getCropCategoryName().equals(castOther.getCropCategoryName())))
				&& ((this.getCropOfferStr() == castOther.getCropOfferStr())
						|| (this.getCropOfferStr() != null && castOther.getCropOfferStr() != null
								&& this.getCropOfferStr().equals(castOther.getCropOfferStr())))
				&& ((this.getOfferDate() == castOther.getOfferDate()) || (this.getOfferDate() != null
						&& castOther.getOfferDate() != null && this.getOfferDate().equals(castOther.getOfferDate())))
				&& ((this.getPrice() == castOther.getPrice()) || (this.getPrice() != null
						&& castOther.getPrice() != null && this.getPrice().equals(castOther.getPrice())))
				&& ((this.getUnit() == castOther.getUnit()) || (this.getUnit() != null && castOther.getUnit() != null
						&& this.getUnit().equals(castOther.getUnit())))
				&& ((this.getUnitName() == castOther.getUnitName()) || (this.getUnitName() != null
						&& castOther.getUnitName() != null && this.getUnitName().equals(castOther.getUnitName())))
				&& ((this.getTodayTrend() == castOther.getTodayTrend()) || (this.getTodayTrend() != null
						&& castOther.getTodayTrend() != null && this.getTodayTrend().equals(castOther.getTodayTrend())))
				&& ((this.getFiveDayTrend() == castOther.getFiveDayTrend())
						|| (this.getFiveDayTrend() != null && castOther.getFiveDayTrend() != null
								&& this.getFiveDayTrend().equals(castOther.getFiveDayTrend())))
				&& ((this.getWeekAverage() == castOther.getWeekAverage())
						|| (this.getWeekAverage() != null && castOther.getWeekAverage() != null
								&& this.getWeekAverage().equals(castOther.getWeekAverage())))
				&& ((this.getWeekTrend() == castOther.getWeekTrend()) || (this.getWeekTrend() != null
						&& castOther.getWeekTrend() != null && this.getWeekTrend().equals(castOther.getWeekTrend())))
				&& ((this.getReason() == castOther.getReason()) || (this.getReason() != null
						&& castOther.getReason() != null && this.getReason().equals(castOther.getReason())))
				&& ((this.getBrowseCount() == castOther.getBrowseCount())
						|| (this.getBrowseCount() != null && castOther.getBrowseCount() != null
								&& this.getBrowseCount().equals(castOther.getBrowseCount())))
				&& ((this.getApprovalState() == castOther.getApprovalState())
						|| (this.getApprovalState() != null && castOther.getApprovalState() != null
								&& this.getApprovalState().equals(castOther.getApprovalState())))
				&& ((this.getReleaseState() == castOther.getReleaseState())
						|| (this.getReleaseState() != null && castOther.getReleaseState() != null
								&& this.getReleaseState().equals(castOther.getReleaseState())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getUserRealName() == castOther.getUserRealName())
						|| (this.getUserRealName() != null && castOther.getUserRealName() != null
								&& this.getUserRealName().equals(castOther.getUserRealName())))
				&& ((this.getOfferDateTime() == castOther.getOfferDateTime())
						|| (this.getOfferDateTime() != null && castOther.getOfferDateTime() != null
								&& this.getOfferDateTime().equals(castOther.getOfferDateTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCropOfferId();
		result = 37 * result + (getRegionCode() == null ? 0 : this.getRegionCode().hashCode());
		result = 37 * result + (getRegionName() == null ? 0 : this.getRegionName().hashCode());
		result = 37 * result + (getCropCategoryCode() == null ? 0 : this.getCropCategoryCode().hashCode());
		result = 37 * result + (getCropCategoryName() == null ? 0 : this.getCropCategoryName().hashCode());
		result = 37 * result + (getCropOfferStr() == null ? 0 : this.getCropOfferStr().hashCode());
		result = 37 * result + (getOfferDate() == null ? 0 : this.getOfferDate().hashCode());
		result = 37 * result + (getPrice() == null ? 0 : this.getPrice().hashCode());
		result = 37 * result + (getUnit() == null ? 0 : this.getUnit().hashCode());
		result = 37 * result + (getUnitName() == null ? 0 : this.getUnitName().hashCode());
		result = 37 * result + (getTodayTrend() == null ? 0 : this.getTodayTrend().hashCode());
		result = 37 * result + (getFiveDayTrend() == null ? 0 : this.getFiveDayTrend().hashCode());
		result = 37 * result + (getWeekAverage() == null ? 0 : this.getWeekAverage().hashCode());
		result = 37 * result + (getWeekTrend() == null ? 0 : this.getWeekTrend().hashCode());
		result = 37 * result + (getReason() == null ? 0 : this.getReason().hashCode());
		result = 37 * result + (getBrowseCount() == null ? 0 : this.getBrowseCount().hashCode());
		result = 37 * result + (getApprovalState() == null ? 0 : this.getApprovalState().hashCode());
		result = 37 * result + (getReleaseState() == null ? 0 : this.getReleaseState().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getUserRealName() == null ? 0 : this.getUserRealName().hashCode());
		result = 37 * result + (getOfferDateTime() == null ? 0 : this.getOfferDateTime().hashCode());
		return result;
	}

	public void setDeleteFlag(String string) {
		// TODO Auto-generated method stub
		
	}

}
