package com.flx.flxoa.info.market.entity;
// Generated 2018-11-9 19:09:53 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HxNewscategory generated by hbm2java
 */
@Entity
@Table(name = "hx_newscategory", catalog = "flxoa")
public class HxNewscategory implements java.io.Serializable {

	private Integer newsCategoryId;
	private String newsCategoryName;
	private Set<HxNews> hxNewses = new HashSet<HxNews>(0);

	public HxNewscategory() {
	}

	public HxNewscategory(String newsCategoryName, Set<HxNews> hxNewses) {
		this.newsCategoryName = newsCategoryName;
		this.hxNewses = hxNewses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "NewsCategoryID", unique = true, nullable = false)
	public Integer getNewsCategoryId() {
		return this.newsCategoryId;
	}

	public void setNewsCategoryId(Integer newsCategoryId) {
		this.newsCategoryId = newsCategoryId;
	}

	@Column(name = "NewsCategoryName", length = 20)
	public String getNewsCategoryName() {
		return this.newsCategoryName;
	}

	public void setNewsCategoryName(String newsCategoryName) {
		this.newsCategoryName = newsCategoryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hxNewscategory")
	public Set<HxNews> getHxNewses() {
		return this.hxNewses;
	}

	public void setHxNewses(Set<HxNews> hxNewses) {
		this.hxNewses = hxNewses;
	}

	public void setDeleteFlag(String string) {
		// TODO Auto-generated method stub
		
	}

}
