package com.flx.flxoa.info.market.entity;
// Generated 2018-11-9 19:09:53 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HxRegion generated by hbm2java
 */
@Entity
@Table(name = "hx_region", catalog = "flxoa")
public class HxRegion implements java.io.Serializable {

	private String regionCode;
	private String region;
	private String parentId;
	private String areaCode;
	private String areaName;
//	private Set<HxCropoffer> hxCropoffers = new HashSet<HxCropoffer>(0);
//	private Set<HxSubscribe> hxSubscribes = new HashSet<HxSubscribe>(0);
//	private Set<HxStatisticsdata> hxStatisticsdatas = new HashSet<HxStatisticsdata>(0);

	public HxRegion() {
	}

	public HxRegion(String regionCode) {
		this.regionCode = regionCode;
	}

	public HxRegion(String regionCode, String region, String parentId, String areaCode, String areaName,Set<HxCropoffer> hxCropoffers,
			Set<HxSubscribe> hxSubscribes, Set<HxStatisticsdata> hxStatisticsdatas) {
		this.regionCode = regionCode;
		this.region = region;
		this.parentId = parentId;
		this.areaCode = areaCode;
		this.areaName = areaName;
//		this.hxCropoffers = hxCropoffers;
//		this.hxSubscribes = hxSubscribes;
//		this.hxStatisticsdatas = hxStatisticsdatas;
	}

	@Id

	@Column(name = "RegionCode", unique = true, nullable = false, length = 6)
	public String getRegionCode() {
		return this.regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	@Column(name = "Region", length = 30)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "ParentId", length = 6)
	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hxRegion")
//	public Set<HxCropoffer> getHxCropoffers() {
//		return this.hxCropoffers;
//	}
//
//	public void setHxCropoffers(Set<HxCropoffer> hxCropoffers) {
//		this.hxCropoffers = hxCropoffers;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hxRegion")
//	public Set<HxSubscribe> getHxSubscribes() {
//		return this.hxSubscribes;
//	}
//
//	public void setHxSubscribes(Set<HxSubscribe> hxSubscribes) {
//		this.hxSubscribes = hxSubscribes;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hxRegion")
//	public Set<HxStatisticsdata> getHxStatisticsdatas() {
//		return this.hxStatisticsdatas;
//	}
//
//	public void setHxStatisticsdatas(Set<HxStatisticsdata> hxStatisticsdatas) {
//		this.hxStatisticsdatas = hxStatisticsdatas;
//	}

	public String getAreaCode() {
		return areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	public String getAreaName() {
		return areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	public void setDeleteFlag(String string) {
		// TODO Auto-generated method stub
		
	}

}
