package com.flx.flxoa.info.market.entity;
// Generated 2018-11-9 19:09:53 by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HxStatisticsdata generated by hbm2java
 */
@Entity
@Table(name = "hx_statisticsdata", catalog = "flxoa")
public class HxStatisticsdata implements java.io.Serializable {

	private Integer statisticsDataId;
	private HxCropcategory hxCropcategory;
	private HxRegion hxRegion;
	private String regionName;
	private String cropCategoryName;
	private String cropOfferStr;
	private Date offerDate;
	private Byte offerWeek;
	private Long price;
	private Integer unit;
	private String unitName;
	private Short offerType;

	public HxStatisticsdata() {
	}

	public HxStatisticsdata(HxCropcategory hxCropcategory, HxRegion hxRegion, String regionName,
			String cropCategoryName, String cropOfferStr, Date offerDate, Byte offerWeek, Long price, Integer unit,
			String unitName, Short offerType) {
		this.hxCropcategory = hxCropcategory;
		this.hxRegion = hxRegion;
		this.regionName = regionName;
		this.cropCategoryName = cropCategoryName;
		this.cropOfferStr = cropOfferStr;
		this.offerDate = offerDate;
		this.offerWeek = offerWeek;
		this.price = price;
		this.unit = unit;
		this.unitName = unitName;
		this.offerType = offerType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "StatisticsDataID", unique = true, nullable = false)
	public Integer getStatisticsDataId() {
		return this.statisticsDataId;
	}

	public void setStatisticsDataId(Integer statisticsDataId) {
		this.statisticsDataId = statisticsDataId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CropCategoryCode")
	public HxCropcategory getHxCropcategory() {
		return this.hxCropcategory;
	}

	public void setHxCropcategory(HxCropcategory hxCropcategory) {
		this.hxCropcategory = hxCropcategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RegionCode")
	public HxRegion getHxRegion() {
		return this.hxRegion;
	}

	public void setHxRegion(HxRegion hxRegion) {
		this.hxRegion = hxRegion;
	}

	@Column(name = "RegionName", length = 30)
	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	@Column(name = "CropCategoryName", length = 50)
	public String getCropCategoryName() {
		return this.cropCategoryName;
	}

	public void setCropCategoryName(String cropCategoryName) {
		this.cropCategoryName = cropCategoryName;
	}

	@Column(name = "CropOfferStr", length = 100)
	public String getCropOfferStr() {
		return this.cropOfferStr;
	}

	public void setCropOfferStr(String cropOfferStr) {
		this.cropOfferStr = cropOfferStr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "OfferDate", length = 10)
	public Date getOfferDate() {
		return this.offerDate;
	}

	public void setOfferDate(Date offerDate) {
		this.offerDate = offerDate;
	}

	@Column(name = "OfferWeek")
	public Byte getOfferWeek() {
		return this.offerWeek;
	}

	public void setOfferWeek(Byte offerWeek) {
		this.offerWeek = offerWeek;
	}

	@Column(name = "Price", precision = 10, scale = 0)
	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

	@Column(name = "Unit")
	public Integer getUnit() {
		return this.unit;
	}

	public void setUnit(Integer unit) {
		this.unit = unit;
	}

	@Column(name = "UnitName", length = 50)
	public String getUnitName() {
		return this.unitName;
	}

	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}

	@Column(name = "OfferType")
	public Short getOfferType() {
		return this.offerType;
	}

	public void setOfferType(Short offerType) {
		this.offerType = offerType;
	}

	public void setDeleteFlag(String string) {
		// TODO Auto-generated method stub
		
	}

}
