package com.flx.flxoa.info.market.entity;
// Generated 2018-11-9 19:09:53 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HxSyslog generated by hbm2java
 */
@Entity
@Table(name = "hx_syslog", catalog = "flxoa")
public class HxSyslog implements java.io.Serializable {

	private Integer sysLogId;
	private Integer userId;
	private String userName;
	private String optTableName;
	private Integer optTableId;
	private Short optType;
	private String optDescription;

	public HxSyslog() {
	}

	public HxSyslog(Integer userId, String userName, String optTableName, Integer optTableId, Short optType,
			String optDescription) {
		this.userId = userId;
		this.userName = userName;
		this.optTableName = optTableName;
		this.optTableId = optTableId;
		this.optType = optType;
		this.optDescription = optDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SysLogID", unique = true, nullable = false)
	public Integer getSysLogId() {
		return this.sysLogId;
	}

	public void setSysLogId(Integer sysLogId) {
		this.sysLogId = sysLogId;
	}

	@Column(name = "UserID")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "UserName", length = 30)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "OptTableName", length = 50)
	public String getOptTableName() {
		return this.optTableName;
	}

	public void setOptTableName(String optTableName) {
		this.optTableName = optTableName;
	}

	@Column(name = "OptTableID")
	public Integer getOptTableId() {
		return this.optTableId;
	}

	public void setOptTableId(Integer optTableId) {
		this.optTableId = optTableId;
	}

	@Column(name = "OptType")
	public Short getOptType() {
		return this.optType;
	}

	public void setOptType(Short optType) {
		this.optType = optType;
	}

	@Column(name = "OptDescription", length = 500)
	public String getOptDescription() {
		return this.optDescription;
	}

	public void setOptDescription(String optDescription) {
		this.optDescription = optDescription;
	}

	public void setDeleteFlag(String string) {
		// TODO Auto-generated method stub
		
	}

}
