package com.flx.flxoa.info.market.entity;
// Generated 2018-12-20 17:01:15 by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HxUser generated by hbm2java
 */
@Entity
@Table(name = "hx_user", catalog = "flxoa")
public class HxUser implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String userRealName;
	private String passWord;
	private String tel;
	private String email;
	private String userType;
	private String tokenId;
	private Date tokenStart;
	private Date tokenTime;
	private Boolean approvalState;
	private Boolean releaseState;

	public HxUser() {
	}

	public HxUser(String userType) {
		this.userType = userType;
	}

	public HxUser(String userName, String userRealName, String passWord, String tel, String email, String userType,
			String tokenId, Date tokenStart, Date tokenTime, Boolean approvalState, Boolean releaseState) {
		this.userName = userName;
		this.userRealName = userRealName;
		this.passWord = passWord;
		this.tel = tel;
		this.email = email;
		this.userType = userType;
		this.tokenId = tokenId;
		this.tokenStart = tokenStart;
		this.tokenTime = tokenTime;
		this.approvalState = approvalState;
		this.releaseState = releaseState;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "UserID", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "UserName", length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "UserRealName", length = 50)
	public String getUserRealName() {
		return this.userRealName;
	}

	public void setUserRealName(String userRealName) {
		this.userRealName = userRealName;
	}

	@Column(name = "PassWord", length = 30)
	public String getPassWord() {
		return this.passWord;
	}

	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}

	@Column(name = "Tel", length = 30)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "Email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "UserType", nullable = false, length = 4)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "TokenID", length = 200)
	public String getTokenId() {
		return this.tokenId;
	}

	public void setTokenId(String tokenId) {
		this.tokenId = tokenId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TokenStart", length = 19)
	public Date getTokenStart() {
		return this.tokenStart;
	}

	public void setTokenStart(Date tokenStart) {
		this.tokenStart = tokenStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TokenTime", length = 19)
	public Date getTokenTime() {
		return this.tokenTime;
	}

	public void setTokenTime(Date tokenTime) {
		this.tokenTime = tokenTime;
	}

	@Column(name = "ApprovalState")
	public Boolean getApprovalState() {
		return this.approvalState;
	}

	public void setApprovalState(Boolean approvalState) {
		this.approvalState = approvalState;
	}

	@Column(name = "ReleaseState")
	public Boolean getReleaseState() {
		return this.releaseState;
	}

	public void setReleaseState(Boolean releaseState) {
		this.releaseState = releaseState;
	}

	public void setDeleteFlag(String string) {
		// TODO Auto-generated method stub
		
	}

}
