package com.flx.flxoa.info.market.entity;
// Generated 2018-11-16 10:52:53 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HxPersonalsubscriptionsdel generated by hbm2java
 */
@Entity
@Table(name = "hx_personalsubscriptionsdel", catalog = "flxoa")
public class HxPersonalsubscriptionsdel implements java.io.Serializable {

	private Integer id;
	private String cropOfferCode;
	private String userId;
	private String subscribeCode;

	public HxPersonalsubscriptionsdel() {
	}

	public HxPersonalsubscriptionsdel(String cropOfferCode, String userId, String subscribeCode) {
		this.cropOfferCode = cropOfferCode;
		this.userId = userId;
		this.subscribeCode = subscribeCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "CropOfferCode", length = 30)
	public String getCropOfferCode() {
		return this.cropOfferCode;
	}

	public void setCropOfferCode(String cropOfferCode) {
		this.cropOfferCode = cropOfferCode;
	}

	@Column(name = "UserID", length = 11)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "SubscribeCode", length = 30)
	public String getSubscribeCode() {
		return this.subscribeCode;
	}

	public void setSubscribeCode(String subscribeCode) {
		this.subscribeCode = subscribeCode;
	}

	public void setDeleteFlag(String string) {
		// TODO Auto-generated method stub
		
	}

}
