package com.flx.flxoa.info.market.entity;
// Generated 2018-11-9 19:09:53 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HxGrade generated by hbm2java
 */
@Entity
@Table(name = "hx_grade", catalog = "flxoa")
public class HxGrade implements java.io.Serializable {

	private Integer gradeId;
	private String gradeName;
	private Set<HxCropoffer> hxCropoffers = new HashSet<HxCropoffer>(0);

	public HxGrade() {
	}

	public HxGrade(String gradeName, Set<HxCropoffer> hxCropoffers) {
		this.gradeName = gradeName;
		this.hxCropoffers = hxCropoffers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "GradeID", unique = true, nullable = false)
	public Integer getGradeId() {
		return this.gradeId;
	}

	public void setGradeId(Integer gradeId) {
		this.gradeId = gradeId;
	}

	@Column(name = "GradeName", length = 20)
	public String getGradeName() {
		return this.gradeName;
	}

	public void setGradeName(String gradeName) {
		this.gradeName = gradeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hxGrade")
	public Set<HxCropoffer> getHxCropoffers() {
		return this.hxCropoffers;
	}

	public void setHxCropoffers(Set<HxCropoffer> hxCropoffers) {
		this.hxCropoffers = hxCropoffers;
	}

	public void setDeleteFlag(String string) {
		// TODO Auto-generated method stub
		
	}

}
