package com.flx.flxoa.info.market.entity;
// Generated 2018-11-9 19:09:53 by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HxAnalysisreport generated by hbm2java
 */
@Entity
@Table(name = "hx_analysisreport", catalog = "flxoa")
public class HxAnalysisreport implements java.io.Serializable {

	private Integer analysisReportId;
	private HxCropcategory hxCropcategory;
	private String cropCategoryName;
	private Date analysisReportDate;
	private String analysisReportName;
	private String analysisReportContent;
	private String attachmentUrl;

	public HxAnalysisreport() {
	}

	public HxAnalysisreport(HxCropcategory hxCropcategory, String cropCategoryName, Date analysisReportDate,
			String analysisReportName, String analysisReportContent, String attachmentUrl) {
		this.hxCropcategory = hxCropcategory;
		this.cropCategoryName = cropCategoryName;
		this.analysisReportDate = analysisReportDate;
		this.analysisReportName = analysisReportName;
		this.analysisReportContent = analysisReportContent;
		this.attachmentUrl = attachmentUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AnalysisReportID", unique = true, nullable = false)
	public Integer getAnalysisReportId() {
		return this.analysisReportId;
	}

	public void setAnalysisReportId(Integer analysisReportId) {
		this.analysisReportId = analysisReportId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CropCategoryCode")
	public HxCropcategory getHxCropcategory() {
		return this.hxCropcategory;
	}

	public void setHxCropcategory(HxCropcategory hxCropcategory) {
		this.hxCropcategory = hxCropcategory;
	}

	@Column(name = "CropCategoryName", length = 50)
	public String getCropCategoryName() {
		return this.cropCategoryName;
	}

	public void setCropCategoryName(String cropCategoryName) {
		this.cropCategoryName = cropCategoryName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "AnalysisReportDate", length = 10)
	public Date getAnalysisReportDate() {
		return this.analysisReportDate;
	}

	public void setAnalysisReportDate(Date analysisReportDate) {
		this.analysisReportDate = analysisReportDate;
	}

	@Column(name = "AnalysisReportName", length = 500)
	public String getAnalysisReportName() {
		return this.analysisReportName;
	}

	public void setAnalysisReportName(String analysisReportName) {
		this.analysisReportName = analysisReportName;
	}

	@Column(name = "AnalysisReportContent", length = 65535)
	public String getAnalysisReportContent() {
		return this.analysisReportContent;
	}

	public void setAnalysisReportContent(String analysisReportContent) {
		this.analysisReportContent = analysisReportContent;
	}

	@Column(name = "AttachmentUrl", length = 500)
	public String getAttachmentUrl() {
		return this.attachmentUrl;
	}

	public void setAttachmentUrl(String attachmentUrl) {
		this.attachmentUrl = attachmentUrl;
	}

	public void setDeleteFlag(String string) {
		// TODO Auto-generated method stub
		
	}

}
