document.writeln("<aside class=\"Hui-aside\">");
document.writeln("	<div class=\"menu_dropdown bk_2\">");
document.writeln("		<dl id=\"menu-article\">");
document.writeln("			<dt><i class=\"Hui-iconfont\">&#xe616;</i> 资讯管理<i class=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i></dt>");
document.writeln("			<dd>");
document.writeln("				<ul>");
document.writeln("					<li><a href=\"article-list.html\" title=\"资讯管理\">资讯管理</a></li>");
document.writeln("				</ul>");
document.writeln("			</dd>");
document.writeln("		</dl>");
document.writeln("		<dl id=\"menu-article\">");
document.writeln("			<dt><i class=\"Hui-iconfont\">&#xe616;</i> 集市管理<i class=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i></dt>");
document.writeln("			<dd>");
document.writeln("				<ul>");
document.writeln("					<li><a href=\"market-list.html\" title=\"集市管理\">集市管理</a></li>");
document.writeln("				</ul>");
document.writeln("			</dd>");
document.writeln("		</dl>");
document.writeln("		<dl id=\"menu-picture\">");
document.writeln("			<dt><i class=\"Hui-iconfont\">&#xe613;</i> 图片管理<i class=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i></dt>");
document.writeln("			<dd>");
document.writeln("				<ul>");
document.writeln("					<li><a href=\"picture-list.html\" title=\"图片管理\">图片管理</a></li>");
document.writeln("				</ul>");
document.writeln("			</dd>");
document.writeln("		</dl>");
document.writeln("		<dl id=\"menu-picture\">");
document.writeln("			<dt><i class=\"Hui-iconfont\">&#xe613;</i> 品牌管理<i class=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i></dt>");
document.writeln("			<dd>");
document.writeln("				<ul>");
document.writeln("					<li><a href=\"brand.html\" title=\"品牌管理\">品牌管理</a></li>");
document.writeln("				</ul>");
document.writeln("			</dd>");
document.writeln("		</dl>");
document.writeln("		<dl id=\"menu-picture\">");
document.writeln("			<dt><i class=\"Hui-iconfont\">&#xe613;</i> 品类管理<i class=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i></dt>");
document.writeln("			<dd>");
document.writeln("				<ul>");
document.writeln("					<li><a href=\"class_list.html\" title=\"品类管理\">分类列表</a></li>");
document.writeln("				</ul>");
document.writeln("			</dd>");
document.writeln("		</dl>");
//document.writeln("		<dl id=\"menu-product\">");
//document.writeln("			<dt><i class=\"Hui-iconfont\">&#xe620;</i> 产品管理<i class=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i></dt>");
//document.writeln("			<dd>");
//document.writeln("				<ul>");
//document.writeln("					<li><a href=\"product-brand.html\" title=\"品牌管理\">品牌管理</a></li>");
//document.writeln("					<li><a href=\"product-category.html\" title=\"分类管理\">分类管理</a></li>");
//document.writeln("					<li><a href=\"product-list.html\" title=\"产品管理\">产品管理</a></li>");
//document.writeln("				</ul>");
//document.writeln("			</dd>");
//document.writeln("		</dl>");
//document.writeln("		<dl id=\"menu-comments\">");
//document.writeln("			<dt><i class=\"Hui-iconfont\">&#xe622;</i> 评论管理<i class=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i></dt>");
//document.writeln("			<dd>");
//document.writeln("				<ul>");
//document.writeln("					<li><a href=\"http://h-ui.duoshuo.com/admin/\" title=\"评论列表\">评论列表</a></li>");
//document.writeln("					<li><a href=\"feedback-list.html\" title=\"意见反馈\">意见反馈</a></li>");
//document.writeln("				</ul>");
//document.writeln("			</dd>");
//document.writeln("		</dl>");
document.writeln("		<dl id=\"menu-member\">");
document.writeln("			<dt><i class=\"Hui-iconfont\">&#xe60d;</i> 会员管理<i class=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i></dt>");
document.writeln("			<dd>");
document.writeln("				<ul>");
document.writeln("					<li><a href=\"member-list.html\" title=\"会员列表\">会员列表</a></li>");
//document.writeln("					<li><a href=\"member-level.html\" title=\"等级管理\">等级管理</a></li>");
//document.writeln("					<li><a href=\"member-scoreoperation.html\" title=\"积分管理\">积分管理</a></li>");
//document.writeln("					<li><a href=\"member-record-browse.html\" title=\"浏览记录\">浏览记录</a></li>");
//document.writeln("					<li><a href=\"member-record-download.html\" title=\"下载记录\">下载记录</a></li>");
//document.writeln("					<li><a href=\"member-record-share.html\" title=\"分享记录\">分享记录</a></li>");
document.writeln("				</ul>");
document.writeln("			</dd>");
document.writeln("		</dl>");
document.writeln("		<dl id=\"menu-admin\">");
document.writeln("			<dt><i class=\"Hui-iconfont\">&#xe62d;</i> 管理员管理<i class=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i></dt>");
document.writeln("			<dd>");
document.writeln("				<ul>");
document.writeln("					<li><a href=\"admin-role.html\" title=\"角色管理\">角色管理</a></li>");
document.writeln("					<li><a href=\"admin-list.html\" title=\"管理员列表\">管理员列表</a></li>");
document.writeln("				</ul>");
document.writeln("			</dd>");
document.writeln("		</dl>");
document.writeln("		<dl id=\"menu-system\">");
document.writeln("			<dt><i class=\"Hui-iconfont\">&#xe62e;</i> 系统管理<i class=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i></dt>");
document.writeln("			<dd>");
document.writeln("				<ul>");
document.writeln("					<li><a href=\"system-base.html\" title=\"系统设置\">系统设置</a></li>");
document.writeln("					<li><a href=\"system-category.html\" title=\"栏目管理\">栏目管理</a></li>");
document.writeln("					<li><a href=\"user_group.html\" title=\"用户组管理\">用户组管理</a></li>");
document.writeln("					<li><a href=\"system-workflow.html\" title=\"工作流管理\">工作流管理</a></li>");
document.writeln("					<li><a href=\"system-data.html\" title=\"数据字典\">数据字典</a></li>");
document.writeln("					<li><a href=\"system-column.html\" title=\"功能管理\">功能管理</a></li>");
document.writeln("					<li><a href=\"system-log.html\" title=\"系统日志\">系统日志</a></li>");
document.writeln("				</ul>");
document.writeln("			</dd>");
document.writeln("		</dl>");
document.writeln("	</div>");
document.writeln("</aside>");
document.writeln("<div class=\"dislpayArrow hidden-xs\"><a class=\"pngfix\" href=\"javascript:void(0);\" onClick=\"displaynavbar(this)\"></a></div>");