package com.flx.flxoa.info.market.entity;
// Generated 2018-12-17 16:47:20 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HxSubscribe generated by hbm2java
 */
@Entity
@Table(name = "hx_subscribe", catalog = "flxoa")
public class HxSubscribe implements java.io.Serializable {

	private Integer subscribeId;
	private String regionCode;
	private String region;
	private String cropCategoryCode;
	private String cropCategoryName;
	private Integer userId;
	private Long price;
	private String cropOfferStr;

	public HxSubscribe() {
	}

	public HxSubscribe(String regionCode, String region, String cropCategoryCode, String cropCategoryName,
			Integer userId, Long price, String cropOfferStr) {
		this.regionCode = regionCode;
		this.region = region;
		this.cropCategoryCode = cropCategoryCode;
		this.cropCategoryName = cropCategoryName;
		this.userId = userId;
		this.price = price;
		this.cropOfferStr = cropOfferStr;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SubscribeID", unique = true, nullable = false)
	public Integer getSubscribeId() {
		return this.subscribeId;
	}

	public void setSubscribeId(Integer subscribeId) {
		this.subscribeId = subscribeId;
	}

	@Column(name = "RegionCode", length = 6)
	public String getRegionCode() {
		return this.regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	@Column(name = "Region", length = 30)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "CropCategoryCode", length = 6)
	public String getCropCategoryCode() {
		return this.cropCategoryCode;
	}

	public void setCropCategoryCode(String cropCategoryCode) {
		this.cropCategoryCode = cropCategoryCode;
	}

	@Column(name = "CropCategoryName", length = 50)
	public String getCropCategoryName() {
		return this.cropCategoryName;
	}

	public void setCropCategoryName(String cropCategoryName) {
		this.cropCategoryName = cropCategoryName;
	}

	@Column(name = "UserID")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "Price", precision = 10, scale = 0)
	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

	@Column(name = "CropOfferStr")
	public String getCropOfferStr() {
		return this.cropOfferStr;
	}

	public void setCropOfferStr(String cropOfferStr) {
		this.cropOfferStr = cropOfferStr;
	}

}
