package com.flx.flxoa.info.market.entity;
// Generated 2018-11-9 19:09:53 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HxFavorite generated by hbm2java
 */
@Entity
@Table(name = "hx_favorite", catalog = "flxoa")
public class HxFavorite implements java.io.Serializable {

	private Integer favoriteId;
	private HxNews hxNews;
	private HxUser hxUser;
	private String title;

	public HxFavorite() {
	}

	public HxFavorite(HxNews hxNews, HxUser hxUser, String title) {
		this.hxNews = hxNews;
		this.hxUser = hxUser;
		this.title = title;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FavoriteID", unique = true, nullable = false)
	public Integer getFavoriteId() {
		return this.favoriteId;
	}

	public void setFavoriteId(Integer favoriteId) {
		this.favoriteId = favoriteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NewsID")
	public HxNews getHxNews() {
		return this.hxNews;
	}

	public void setHxNews(HxNews hxNews) {
		this.hxNews = hxNews;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID")
	public HxUser getHxUser() {
		return this.hxUser;
	}

	public void setHxUser(HxUser hxUser) {
		this.hxUser = hxUser;
	}

	@Column(name = "Title", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public void setDeleteFlag(String string) {
		// TODO Auto-generated method stub
		
	}

}
