package com.flx.flxoa.info.market.entity;
// Generated 2018-11-9 19:09:53 by Hibernate Tools 5.1.7.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * HxSubscribecount generated by hbm2java
 */
@Entity
@Table(name = "hx_subscribecount", catalog = "flxoa")
public class HxSubscribecount implements java.io.Serializable {

	private HxSubscribecountId id;
	private Integer subscribeCount;

	public HxSubscribecount() {
	}

	public HxSubscribecount(HxSubscribecountId id) {
		this.id = id;
	}

	public HxSubscribecount(HxSubscribecountId id, Integer subscribeCount) {
		this.id = id;
		this.subscribeCount = subscribeCount;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "regionCode", column = @Column(name = "RegionCode", nullable = false, length = 6)),
			@AttributeOverride(name = "cropCategoryCode", column = @Column(name = "CropCategoryCode", nullable = false, length = 6)) })
	public HxSubscribecountId getId() {
		return this.id;
	}

	public void setId(HxSubscribecountId id) {
		this.id = id;
	}

	@Column(name = "SubscribeCount")
	public Integer getSubscribeCount() {
		return this.subscribeCount;
	}

	public void setSubscribeCount(Integer subscribeCount) {
		this.subscribeCount = subscribeCount;
	}

}
