package com.flx.flxoa.info.market.entity;
// Generated 2018-11-9 19:09:53 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HxSubscribecountId generated by hbm2java
 */
@Embeddable
public class HxSubscribecountId implements java.io.Serializable {

	private String regionCode;
	private String cropCategoryCode;

	public HxSubscribecountId() {
	}

	public HxSubscribecountId(String regionCode, String cropCategoryCode) {
		this.regionCode = regionCode;
		this.cropCategoryCode = cropCategoryCode;
	}

	@Column(name = "RegionCode", nullable = false, length = 6)
	public String getRegionCode() {
		return this.regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	@Column(name = "CropCategoryCode", nullable = false, length = 6)
	public String getCropCategoryCode() {
		return this.cropCategoryCode;
	}

	public void setCropCategoryCode(String cropCategoryCode) {
		this.cropCategoryCode = cropCategoryCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HxSubscribecountId))
			return false;
		HxSubscribecountId castOther = (HxSubscribecountId) other;

		return ((this.getRegionCode() == castOther.getRegionCode()) || (this.getRegionCode() != null
				&& castOther.getRegionCode() != null && this.getRegionCode().equals(castOther.getRegionCode())))
				&& ((this.getCropCategoryCode() == castOther.getCropCategoryCode())
						|| (this.getCropCategoryCode() != null && castOther.getCropCategoryCode() != null
								&& this.getCropCategoryCode().equals(castOther.getCropCategoryCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRegionCode() == null ? 0 : this.getRegionCode().hashCode());
		result = 37 * result + (getCropCategoryCode() == null ? 0 : this.getCropCategoryCode().hashCode());
		return result;
	}

}
