document.writeln("<header class=\"navbar-wrapper\">");
document.writeln("	<div class=\"navbar navbar-fixed-top\">");
document.writeln("		<div class=\"container-fluid cl\"> <a class=\"logo navbar-logo f-l mr-10 hidden-xs\" href=\"/aboutHui.shtml\">信息超市</a>");
document.writeln("			<nav class=\"nav navbar-nav\">");
document.writeln("				<ul class=\"cl\">");
document.writeln("					<li class=\"dropDown dropDown_hover\"><a href=\"javascript:;\" class=\"dropDown_A\"><i class=\"Hui-iconfont\">&#xe600;</i> 新增 <i class=\"Hui-iconfont\">&#xe6d5;</i></a>");
document.writeln("						<ul class=\"dropDown-menu menu radius box-shadow\">");
document.writeln("							<li><a href=\"javascript:;\" onclick=\"article_add(\'添加资讯\',\'article-add.html\')\"><i class=\"Hui-iconfont\">&#xe616;</i> 资讯</a></li>");
document.writeln("							<li><a href=\"javascript:;\" onclick=\"picture_add(\'添加资讯\',\'picture-add.html\')\"><i class=\"Hui-iconfont\">&#xe613;</i> 图片</a></li>");
document.writeln("							<li><a href=\"javascript:;\" onclick=\"product_add(\'添加资讯\',\'product-add.html\')\"><i class=\"Hui-iconfont\">&#xe620;</i> 产品</a></li>");
document.writeln("							<li><a href=\"javascript:;\" onclick=\"member_add(\'添加用户\',\'member-add.html\',\'\',\'510\')\"><i class=\"Hui-iconfont\">&#xe60d;</i> 用户</a></li>");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</nav>");
document.writeln("			<nav id=\"Hui-userbar\" class=\"nav navbar-nav navbar-userbar hidden-xs\">");
document.writeln("				<ul class=\"cl\">");
document.writeln("					<li>超级管理员</li>");
document.writeln("					<li class=\"dropDown dropDown_hover\"> <a href=\"#\" class=\"dropDown_A\">admin <i class=\"Hui-iconfont\">&#xe6d5;</i></a>");
document.writeln("						<ul class=\"dropDown-menu menu radius box-shadow\">");
document.writeln("							<li><a href=\"javascript:;\" onClick=\"myselfinfo()\">个人信息</a></li>");
document.writeln("							<li><a href=\"#\">切换账户</a></li>");
document.writeln("							<li><a href=\"#\">退出</a></li>");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("					<li id=\"Hui-msg\"> <a href=\"#\" title=\"消息\"><span class=\"badge badge-danger\">1</span><i class=\"Hui-iconfont\" style=\"font-size:18px\">&#xe68a;</i></a> </li>");
document.writeln("					<li id=\"Hui-skin\" class=\"dropDown right dropDown_hover\"> <a href=\"javascript:;\" class=\"dropDown_A\" title=\"换肤\"><i class=\"Hui-iconfont\" style=\"font-size:18px\">&#xe62a;</i></a>");
document.writeln("						<ul class=\"dropDown-menu menu radius box-shadow\">");
document.writeln("							<li><a href=\"javascript:;\" data-val=\"default\" title=\"默认（黑色）\">默认（黑色）</a></li>");
document.writeln("							<li><a href=\"javascript:;\" data-val=\"blue\" title=\"蓝色\">蓝色</a></li>");
document.writeln("							<li><a href=\"javascript:;\" data-val=\"green\" title=\"绿色\">绿色</a></li>");
document.writeln("							<li><a href=\"javascript:;\" data-val=\"red\" title=\"红色\">红色</a></li>");
document.writeln("							<li><a href=\"javascript:;\" data-val=\"yellow\" title=\"黄色\">黄色</a></li>");
document.writeln("							<li><a href=\"javascript:;\" data-val=\"orange\" title=\"橙色\">橙色</a></li>");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</nav>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("</header>");
document.writeln("");