package com.flx.flxoa.info.market.entity;
// Generated 2018-11-9 19:09:53 by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HxNews generated by hbm2java
 */
@Entity
@Table(name = "hx_news", catalog = "flxoa")
public class HxNews implements java.io.Serializable {

	private Integer newsId;
	private HxNewscategory hxNewscategory;
	private HxSource hxSource;
	private String title;
	private String content;
	private String newsCategoryName;
	private Date publishDt;
	private String sourceName;
	private String imgUrl;
	private Boolean approvalState;
	private Boolean releaseState;
	private Set<HxFavorite> hxFavorites = new HashSet<HxFavorite>(0);

	public HxNews() {
	}

	public HxNews(HxNewscategory hxNewscategory, HxSource hxSource, String title, String content,
			String newsCategoryName, Date publishDt, String sourceName, String imgUrl, Boolean approvalState,
			Boolean releaseState, Set<HxFavorite> hxFavorites) {
		this.hxNewscategory = hxNewscategory;
		this.hxSource = hxSource;
		this.title = title;
		this.content = content;
		this.newsCategoryName = newsCategoryName;
		this.publishDt = publishDt;
		this.sourceName = sourceName;
		this.imgUrl = imgUrl;
		this.approvalState = approvalState;
		this.releaseState = releaseState;
		this.hxFavorites = hxFavorites;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "NewsID", unique = true, nullable = false)
	public Integer getNewsId() {
		return this.newsId;
	}

	public void setNewsId(Integer newsId) {
		this.newsId = newsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NewsCategoryID")
	public HxNewscategory getHxNewscategory() {
		return this.hxNewscategory;
	}

	public void setHxNewscategory(HxNewscategory hxNewscategory) {
		this.hxNewscategory = hxNewscategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SourceCode")
	public HxSource getHxSource() {
		return this.hxSource;
	}

	public void setHxSource(HxSource hxSource) {
		this.hxSource = hxSource;
	}

	@Column(name = "Title", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "NewsCategoryName", length = 20)
	public String getNewsCategoryName() {
		return this.newsCategoryName;
	}

	public void setNewsCategoryName(String newsCategoryName) {
		this.newsCategoryName = newsCategoryName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PublishDt", length = 19)
	public Date getPublishDt() {
		return this.publishDt;
	}

	public void setPublishDt(Date publishDt) {
		this.publishDt = publishDt;
	}

	@Column(name = "SourceName", length = 50)
	public String getSourceName() {
		return this.sourceName;
	}

	public void setSourceName(String sourceName) {
		this.sourceName = sourceName;
	}

	@Column(name = "ImgUrl", length = 300)
	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	@Column(name = "ApprovalState")
	public Boolean getApprovalState() {
		return this.approvalState;
	}

	public void setApprovalState(Boolean approvalState) {
		this.approvalState = approvalState;
	}

	@Column(name = "ReleaseState")
	public Boolean getReleaseState() {
		return this.releaseState;
	}

	public void setReleaseState(Boolean releaseState) {
		this.releaseState = releaseState;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hxNews")
	public Set<HxFavorite> getHxFavorites() {
		return this.hxFavorites;
	}

	public void setHxFavorites(Set<HxFavorite> hxFavorites) {
		this.hxFavorites = hxFavorites;
	}

	public void setDeleteFlag(String string) {
		// TODO Auto-generated method stub
		
	}

}
